/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0b1f4071 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/ncbwummxjmsfcreagnmz/database/tables

// This file provides a simple key-value interface for storing Figma Make data.
// Return types use `any` deliberately so callers can type-assert as needed
// without triggering "unknown is not assignable to T" TypeScript errors.
import { createClient } from "jsr:@supabase/supabase-js@2";

// deno-lint-ignore no-explicit-any
type AnyJson = any;

const client = () => createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: AnyJson): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_0b1f4071").upsert({ key, value });
  if (error) throw new Error(error.message);
};

// Get retrieves a value by key. Returns `any` so callers can cast freely.
// deno-lint-ignore no-explicit-any
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_0b1f4071")
    .select("value")
    .eq("key", key)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value ?? null;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_0b1f4071").delete().eq("key", key);
  if (error) throw new Error(error.message);
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: AnyJson[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_0b1f4071")
    .upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) throw new Error(error.message);
};

// Gets multiple values by key array. Returns any[] so callers can cast freely.
// deno-lint-ignore no-explicit-any
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_0b1f4071")
    .select("value")
    .in("key", keys);
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_0b1f4071").delete().in("key", keys);
  if (error) throw new Error(error.message);
};

// Search for values whose key starts with `prefix`. Returns any[] so callers
// can apply typed callbacks (e.g. .filter((x: MyType) => ...)) without errors.
// deno-lint-ignore no-explicit-any
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_0b1f4071")
    .select("key, value")
    .like("key", prefix + "%");
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};

// List keys matching a glob-style pattern (* → SQL %).
export const listKeys = async (pattern: string): Promise<string[]> => {
  const supabase = client();
  const likePattern = pattern.replace(/\*/g, "%");
  const { data, error } = await supabase
    .from("kv_store_0b1f4071")
    .select("key")
    .like("key", likePattern);
  if (error) throw new Error(error.message);
  return data?.map((d) => d.key) ?? [];
};
